services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3100:3100"


    
